apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lalavisit-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: lalavisit
    environment: development
spec:
  project: default

  source:
    repoURL: https://github.com/e16tae/lalavisit.git  # CHANGE THIS to your repo URL
    targetRevision: develop
    path: k8s/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: lalavisit

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
