apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: lalavisit
spec:
  template:
    metadata:
      annotations:
        # This annotation triggers rolling update when changed by CI/CD
        # Updated automatically by GitHub Actions on each deployment
        deployment.kubernetes.io/revision: "2be4f60e24bcb87ecf5b7937a8b2dd9679bdb023-2025-10-14T07:35:25Z"
