# IMPORTANT: This is a template file for production secrets
# DO NOT commit actual secrets to Git
#
# To apply production secrets, use kubectl directly:
#
#   kubectl create secret generic lalavisit-secrets \
#     --from-literal=email-user=lalavisit@naver.com \
#     --from-literal=email-password=YOUR_ACTUAL_PASSWORD \
#     --from-literal=smtp-host=smtp.naver.com \
#     --from-literal=smtp-port=587 \
#     --from-literal=contact-email=lalavisit@naver.com \
#     --namespace=lalavisit \
#     --dry-run=client -o yaml | kubectl apply -f -
#
# Or use a secret management tool like:
# - Sealed Secrets: https://github.com/bitnami-labs/sealed-secrets
# - External Secrets Operator: https://external-secrets.io/
# - Kubernetes Secret Store CSI Driver

apiVersion: v1
kind: Secret
metadata:
  name: lalavisit-secrets
  namespace: lalavisit
type: Opaque
stringData:
  # PLACEHOLDER VALUES - DO NOT USE IN PRODUCTION
  # Replace these with actual values using kubectl or a secret management tool
  email-user: "REPLACE_WITH_ACTUAL_EMAIL"
  email-password: "REPLACE_WITH_ACTUAL_PASSWORD"
  smtp-host: "smtp.naver.com"
  smtp-port: "587"
  contact-email: "REPLACE_WITH_ACTUAL_EMAIL"
