# IMPORTANT: This is a template file
# DO NOT commit actual secrets to Git
#
# Sealed Secrets 워크플로를 사용할 때는 이 템플릿을 참고하여 `.env.production`을 구성한 뒤
# `./scripts/seal-secrets.sh` 스크립트를 실행하세요. 생성된 SealedSecret은
# `k8s/sealed-secrets/` 디렉터리에 저장됩니다.

apiVersion: v1
kind: Secret
metadata:
  name: lalavisit-secrets
  namespace: lalavisit
type: Opaque
stringData:
  # PLACEHOLDER VALUES - Replace with actual values or use secret management tool
  email-user: "REPLACE_ME"
  email-password: "REPLACE_ME"
  smtp-host: "REPLACE_ME"
  smtp-port: "REPLACE_ME"
  contact-email: "REPLACE_ME"
