name: CI - Develop Branch

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/**'
      - '!.github/workflows/**'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'

permissions:
  contents: read

jobs:
  quality-checks:
    name: Quality Checks
    uses: ./.github/workflows/quality-checks.yaml
    with:
      node-version: '22'
      site-url: 'https://dev.lalavisit.com'

  docker-build-test:
    name: Docker Build Test
    runs-on: ubuntu-latest
    needs: quality-checks
    timeout-minutes: 15
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: lalavisit-frontend:dev-${{ github.sha }}
          build-args: |
            NEXT_PUBLIC_SITE_URL=https://dev.lalavisit.com
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Report success
        run: |
          echo "## ✅ CI Passed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All quality checks and Docker build test completed successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch**: \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Docker Image Tag**: \`lalavisit-frontend:dev-${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
