name: Quality Checks (Reusable)

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: '22'
      site-url:
        description: 'Site URL for build'
        required: false
        type: string
        default: 'https://www.lalavisit.com'
    secrets:
      KAKAO_CHANNEL_ID:
        required: false
      GOOGLE_VERIFICATION:
        required: false
      NAVER_VERIFICATION:
        required: false

jobs:
  quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run type check
        run: npx tsc --noEmit

      - name: Build verification
        env:
          NEXT_PUBLIC_SITE_URL: ${{ inputs.site-url }}
          NEXT_PUBLIC_KAKAO_CHANNEL_ID: ${{ secrets.KAKAO_CHANNEL_ID }}
          NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION: ${{ secrets.GOOGLE_VERIFICATION }}
          NEXT_PUBLIC_NAVER_SITE_VERIFICATION: ${{ secrets.NAVER_VERIFICATION }}
        run: npm run build

      - name: Report build size
        run: |
          echo "## 📦 Build Output" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          du -sh .next | awk '{print "Total build size: " $1}' >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
